web.mydomain.local
##SAMPLE
BAL-OK-01 ansible_host=10.129.33.108 internalIP=10.16.30.108
BAL-OK-02 ansible_host=10.129.33.109 internalIP=10.16.30.109
BAL-OK-03 ansible_host=10.129.33.110 internalIP=10.16.30.110
BAL-OK-04 ansible_host=10.129.33.111 internalIP=10.16.30.111
BAL-OK-05 ansible_host=10.129.33.112 internalIP=10.16.30.112

BAL-ZZ-01 ansible_host=10.129.33.113 internalIP=10.16.30.113
BAL-ZZ-02 ansible_host=10.129.33.114 internalIP=10.16.30.114
BAL-ZZ-03 ansible_host=10.129.33.115 internalIP=10.16.30.115

BAL-ZZ-01 ansible_host=10.129.33.121 internalIP=10.16.38.121 serviceIP=10.16.31.121
BAL-ZZ-02 ansible_host=10.129.33.122 internalIP=10.16.38.122 serviceIP=10.16.31.122
BAL-ZZ-03 ansible_host=10.129.33.123 internalIP=10.16.38.123 serviceIP=10.16.31.123

zultest-01 ansible_host=10.79.100.122 internalIP=10.79.100.122

[vm]
192.168.0.11
192.168.0.12

[alma]
192.168.0.8

[lab]
# To secure the password with ansible vault, follow these steps:
# 1. Create an encrypted variable file: ansible-vault create group_vars/lab/vault.yml (pw = vault)
# 2. Add the password to the vault file: vault_ansible_ssh_pass: Riedel1!
# 3. Replace the plain text password with the vault variable reference
## TODO: seems cannot used vault here, so use plain text for now.
zultest-01 ansible_user=riedel ansible_ssh_pass=Riedel1! ansible_become_pass=Riedel1!
##SAMPLE
[test-wave]
BAL=OK-[01:03]

[test:children]
vm
alma

[nginx]
zultest-01 ansible_user=riedel ansible_ssh_pass=Riedel1! ansible_become_pass=Riedel1!
